### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by emhart** [ropensci/rgpdd#1]
I looked into this awhile back with interest, and they didn't have an API as far as I could tell.  Are they getting one, or what's the plan with this? (Just because I'm interested in developing it as well).

**Comment by cboettig** [comment]
No API, but given the small data byte-size and the fact that the database may be updated less than once a decade, a data package will offer better performance anyhow.  Since reading in the data is something of nuisance as it stands (in particular, isn't portable do to the MS dependencies), I think there may be ample utility in a package that facilitates this access; which is very much in spirit with the declared objectives of the GPDD.  I did contact the DB administrator to let them know about the package goals and issues with access currently back when this issue was last active (Sept 19, 2013), but haven't (yet) received any reply.
