### ISSUE TITLE
Openness to integrating retrieval of external associated data

### ISSUE THREAD

**Issue by ethanwhite** [ropensci/rgpdd#5]
I have a student in my semester long Data Carpentry course who has been working with GPDD data and collecting a bunch of supplemental data associated with each dataset. For his class project he's interested in working towards making this data publicly available and useful through `rgpdd`. If he were to publicly archive his data (either now or in the future; details are still unclear) would you be open to a PR pulling in that helper data in some way.

Of course I'd totally understand if you want to keep this purely focused on the official GPDD, which is why I'm asking before trying to encourage him in this direction.

**Comment by sckott** [comment]
@cboettig Let me know if you have time to answer this - if not I'll dig in

**Comment by karthik** [comment]
> If he were to publicly archive his data (either now or in the future; details are still unclear) would you be open to a PR pulling in that helper data in some way.

Seems like a great idea to me. I love that your students and team have become regular contributors to the project. 👍

**Comment by cboettig** [comment]
Hi Ethan,

Sounds awesome.  I'm rethinking a bit about how rgpdd should work so that this is all easier and less specific.  

In particular, as you may have seen, we got the GPDD migrated from that old Imperial College website / request access thing into a public database on the KNB with a DOI, [10.5063/F1BZ63Z8](http://dx.doi.org10.5063/F1BZ63Z8).  All the tables are available on the KNB as CSV files instead of a stupid MS Access database, so they should be easier to work with; and we have EML metadata available for all the tables.

I'm now working with an undergrad student (Anna, the same one that was working with the Portal data we discussed in https://github.com/weecology/PortalData/issues/25) to 'atomize' this GPDD data (or at least the metadata associated with each individual dataset). This would make it easier for a search on KNB for a particular species or area to return the relevant data from the GPDD (along with any other similar data on KNB), since we generate EML metadata for each dataset instead of just having it for the GPDD tables as a whole.  We have shown that we can essentially re-assemble the GPDD on the fly from its 'atomized' individual data sets using the EML. 

The upshot of all of this is that it should be easy to essentially 'extend' the GPDD data with additional supplemental data just by archiving the new data with an EML file in the KNB.  (Working on making that step easier & programmatic using our EML package and the DataONE R package, which should be done soon. But can also be done with other toolchains).  

I think this has a big advantage in being a more language-agnostic approach that benefits from the permanent archiving, discoverability and DOIs we get from the KNB.  

As for rgpdd, I suppose it could become / be replaced by a simple wrapper around dataone & EML packages that could query the desired data from the canonical source on the KNB, and then download the subset of the data of interest, along with associated metadata.  

Really interested in feedback on this and would love to see your student give this a whirl for his supplemental data.  (All the infrastructure is basically in place on our end now, just doing this kind of testing / working up use cases now).  Thanks!

**Comment by ethanwhite** [comment]
Thanks all!

@cboettig - Great! Yeah, I'm really glad that you got that data out of the old system and into something more open and usable. The atomization idea is really interesting and I can definitely see big advantages in the long-run. I'll pass this information along to the student and hopefully he'll get far enough in his project that we can start engaging with you later in the semester on details. I'll go ahead and close this for the time being and be back in touch further down the line if the student is on board with everything.
