### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by ha0ye** [ropensci/rgpdd#6]
@cboettig Do you have any info or updates on this project? We have this as a dependency over in https://github.com/weecology/MATSS, and if this is no longer being maintained, what should we consider for access to the GPDD?

**Comment by cboettig** [comment]
Thanks!  I had a student create an updated version of this over at https://github.com/boettiger-lab/gpdd, I should probably migrate this to point there.  Though really that implementation is so trivial that it's probably better to just grab the data directly from the https://doi.org/10.5063/F1BZ63Z8

(Backstory: at the time I wrote this `rgpdd`, there wasn't a DOI-hosted version and accessing this data could be annoying.  We worked with Matt Jones and the folks at Imperial to get the GPDD onto KNB, with proper EML metadata etc, which made this package irrelevant.  I thought about https://github.com/boettiger-lab/gpdd as a nice student project mostly to stand in place of this old repo, but I'm kinda on the fence about the whole idea of having a package instead of just saying "get the data at https://doi.org/10.5063/F1BZ63Z8".  (e.g. rOpenSci editors rejected the `gpdd` package as too trivial, see https://github.com/ropensci/software-review/issues/310 :-) )

**Comment by ha0ye** [comment]
Thanks! This should be sufficient info for us to figure out how we want to move forward on our end. 👍
